version: "2"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: backend/.docker-env/database
    ports:
      - "5432:5432"

  redis:
    image: redis:3.0
  backend:
    # image: raw2dng_api
    build:
      context: backend
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - /media:/media
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    env_file: backend/.docker-env/backend
    depends_on:
      - db
      - redis

volumes:
  postgres_data: