version: "2"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: raw2dng_api
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - media_data:/app/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DOCKERIZE=true
    # env_file: .env-docker
    depends_on:
      - db

volumes:
  postgres_data:
  media_data: