# Generated by Django 4.1 on 2022-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('extension', models.CharField(default='ARW', max_length=4)),
                ('user', models.CharField(max_length=120)),
                ('source', models.FileField(blank=True, upload_to='')),
                ('converted', models.BooleanField(default=False)),
                ('converted_source', models.FileField(blank=True, default=None, upload_to='')),
            ],
        ),
    ]
