# Generated by Django 4.1 on 2022-09-04 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimage',
            name='completed',
        ),
        migrations.AddField(
            model_name='rawimage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawimage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rawimage',
            name='source',
            field=models.FileField(upload_to=''),
        ),
    ]
