# Generated by Django 4.1 on 2022-09-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='extension',
        ),
    ]
