# Generated by Django 4.1 on 2022-09-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0002_remove_image_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='converted_source',
            new_name='converted_image',
        ),
    ]
