# Generated by Django 4.1 on 2022-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0002_remove_rawimage_completed_rawimage_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimage',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='rawimage',
            name='source',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
