# Generated by Django 4.1 on 2022-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0003_rename_converted_source_image_converted_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='converted_image',
            new_name='converted_source',
        ),
        migrations.AlterField(
            model_name='image',
            name='converted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
