# Generated by Django 4.1 on 2022-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0003_remove_rawimage_date_updated_alter_rawimage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimage',
            name='user',
            field=models.CharField(default='valentin', max_length=120),
        ),
    ]
