# Generated by Django 4.1 on 2022-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0004_rawimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimage',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
