# Generated by Django 4.1 on 2022-09-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0004_rename_converted_image_image_converted_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='converted_source',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
