# Generated by Django 4.1 on 2022-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0006_alter_image_converted_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=120)),
                ('source', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.FileField(upload_to=''),
        ),
    ]
