# Generated by Django 4.1 on 2022-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0007_convertedimage_alter_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
