# Generated by Django 4.1 on 2022-09-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0008_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.CharField(auto_created=True, blank=True, max_length=120),
        ),
    ]
