# Generated by Django 4.1 on 2022-09-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0009_alter_image_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertedImage',
        ),
    ]
