# Generated by Django 4.1 on 2022-09-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw2dng', '0010_delete_convertedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(upload_to=''),
        ),
    ]
